import { Heading, Padding, Wrapper } from '@components/display'

export default () => (
  <div>
    <Heading level="h1">Welcome to next.js!</Heading>
    <Heading level="h2">Welcome to next.js!</Heading>
    <Heading level="h3">Welcome to next.js!</Heading>
    <Heading level="h4">Welcome to next.js!</Heading>
    <Heading level="h5">Welcome to next.js!</Heading>
    <Heading level="h6">Welcome to next.js!</Heading>
    <Wrapper size="extra-small">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Wrapper>
    <Wrapper size="small">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Wrapper>
    <Wrapper size="medium">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Wrapper>
    <Wrapper size="large">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Wrapper>
    <Wrapper size="extra-large">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Wrapper>
    <Padding size="extra-small">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Padding>
    <Padding size="small">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Padding>
    <Padding size="medium">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Padding>
    <Padding size="large">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Padding>
    <Padding size="extra-large">Anim irure fugiat reprehenderit velit sunt duis tempor laborum reprehenderit. Laboris nostrud irure laborum consequat minim ipsum ex duis adipisicing proident in quis officia labore. Aliqua ea cillum ex veniam cillum quis do cupidatat minim consequat ea ut consequat consequat. Ut amet velit proident labore anim occaecat id pariatur do consequat velit. Eiusmod dolore cupidatat esse eu exercitation et eu eu esse excepteur adipisicing aute consectetur enim. Commodo commodo aliquip sunt occaecat labore ut labore enim nostrud ad voluptate mollit ut. Amet incididunt aliqua aute ullamco sint exercitation id. Irure consequat consectetur qui laborum sunt in irure enim nostrud irure nostrud dolor et. Ad elit sunt id amet occaecat cupidatat adipisicing magna dolor Lorem labore.</Padding>
  </div>
)
